# 这是一个基础的 SpaceVim 配置示例

# 所有的 SpaceVim 选项都列在 [options] 之下
[options]
    # 设置 SpaceVim 主题及背景，默认的主题是 gruvbox，如果你需要使用更
    # 多的主题，你可以载入 colorscheme 模块
    colorscheme = "onedark"
    # 背景可以取值 "dark" 或 "light"
    colorscheme_bg = "dark"
    # 启用/禁用终端真色，在目前大多数终端下都是支持真色的，当然也有
    # 一小部分终端不支持真色，如果你的 SpaceVim 颜色看上去比较怪异
    # 可以禁用终端真色，将下面的值设为 false
    enable_guicolors = true 
    # 设置状态栏上分割符号形状，如果字体安装失败，可以将值设为 "nil" 以
    # 禁用分割符号，默认为箭头 "arrow"
    statusline_separator = "arrow"
    statusline_inactive_separator = "bar"
    # 设置顶部标签列表序号类型，有以下五种类型，分别是 0 - 4
    # 0: 1 ➛ ➊
    # 1: 1 ➛ ➀
    # 2: 1 ➛ ⓵
    # 3: 1 ➛ ¹
    # 4: 1 ➛ 1
    buffer_index_type = 0 
    # 显示/隐藏顶部标签栏上的文件类型图标，这一图标需要安装 nerd fonts，
    # 如果未能成功安装这一字体，可以隐藏图标
    enable_tabline_filetype_icon = true
    # 是否在状态栏上显示当前模式，默认情况下，不显示 Normal/Insert 等
    # 字样，只以颜色区分当前模式
    enable_statusline_mode = true 
    # 状态栏左端部分的构成
    statusline_left_sections = ['winnr', 'major mode', 'filename', 'fileformat', 'minor mode lighters', 'version control info', 'search status']
    # 状态栏右端部分的构成
    statusline_right_sections = ['cursorpos', 'percentage', 'input method', 'date', 'time']
    # 列表可以由以下一项或多项组成

    # 'winnr' 当前窗口编号
    # 'syntax checking'
    # 'filename' 文件名
    # 'fileformat' 文件格式
    # 'major mode'
    # 'minor mode lighters'
    # 'cursorpos' 光标位置
    # 'percentage' 百分比
    # 'date' 日期
    # 'time' 时间
    # 'whitespace' 打开或者保存文件时，如果第 n 行的行尾有空格则显示 trailing[n]，并不能实时显示出行尾有空格的行号。
    # 'battery status' 电池状态
    # 'input method' 输入法
    # 'search status' 搜索状态

    enable_tabline_filetype_icon = false

    enable_ale = true
    enable_ycm = true

    bootstrap_after="myspacevim#after"
    bootstrap_before="myspacevim#before"

    snippet_engine = "ultisnips"
    filemanager = "nerdtree"

# SpaceVim 模块设置，主要包括启用/禁用模块
# 启用youcompleteme

# 启用 autocomplete 模块，启用模块时，可以列出一些模块选项，并赋值，
# 关于模块的选项，请阅读各个模块的文档
[[layers]]
    name = "autocomplete"
    auto-completion-return-key-behavior = "smart"
    auto-completion-tab-key-behavior = "smart"
    auto-completion-delay = 200
    auto-completion-complete-with-key-sequence = "nil"
    auto-completion-complete-with-key-sequence-delay = 0.1

# 禁用 shell 模块，禁用模块时，需要加入 enable = false
[[layers]]
    name = "shell"
    default_position = "bottom"
    default_height = 15 
    enable = true

#[[layers]]
#name = "cscope"

[[layers]]
  name = "ctrlp"

[[layers]]
  name = "ui"

[[layers]]
  name = "debug"

#[[layers]]
#  name = "unite"

#[[layers]]
#  name = "denite"

[[layers]]
  name = "fzf"

[[layers]]
  name = "core#statusline"

[[layers]]
    name = "incsearch"

[[layers]]
    name = "lang#python"

[[layers]]
    name = "lang#c"

[[layers]]
    name = "git"

[[layers]]
    name = "github"

[[layers]]
    name = "lang#sh"

[[layers]]
    name = "lang#vim"

[[layers]]
    name = "lang#markdown"

#[[layers]]
#    name = "leaderf"

#[[layers]]
#  name = "lsp"
#  filetypes = [
#    "c",
#    "c++",
#    "python"
#  ]
#  [layers.override_cmd]
#    rust = ["rustup", "run", "nightly", "rls"]
#https://spacevim.org/cn/layers/language-server-protocol/

[[layers]]
    name = "format"

[[layers]]
    name = "VersionControl"

[[layers]]
    name = "autocomplete"

[[layers]]
    name = "chat"

[[layers]]
    name = "tags"

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "gtags"
  gtagslabel = "Universal ctags"


# 添加自定义插件
[[custom_plugins]]
    name = "lilydjwg/colorizer"
    merged = false

[[custom_plugins]]
  name = "mhartington/oceanic-next"
  merged = 0

[[custom_plugins]]
  name = "octol/vim-cpp-enhanced-highlight"
  merged = 0

[[custom_plugins]]
  name = "vim-scripts/a.vim"
  merged = 0

[[custom_plugins]]
  name = "rdnetto/YCM-Generator"
  merged = 0

[[custom_plugins]]
  name = "christoomey/vim-tmux-navigator"
  merged = 0

[[custom_plugins]]
  name = "iamcco/markdown-preview.nvim"
  merged = 0

[[custom_plugins]]
  name = "ludovicchabant/vim-gutentags"
  merged = 0

[[custom_plugins]]
  name = "skywind3000/gutentags_plus"
  merged = 0

[[custom_plugins]]
  name = "joereynolds/gtags-scope"
  merged = 0

[[custom_plugins]]
  name = "skywind3000/vim-preview"
  merged = 0

[[custom_plugins]]
  name = "skywind3000/asyncrun.vim"
  merged = 0

[[custom_plugins]]
  name = "davidhalter/jedi-vim"
  merged = 0

[[custom_plugins]]
  name = "scrooloose/syntastic"
  merged = 0

[[custom_plugins]]
  name = "Xuyuanp/nerdtree-git-plugin"
  merged = 0

[[custom_plugins]]
  name = "tiagofumo/vim-nerdtree-syntax-highlight"
  merged = 0
